### ISSUE TITLE
关掉视频中的帧率等信息

### ISSUE THREAD

**Issue by zhangfeisysu** [Rukey7/IjkPlayerView#1]
请教下您是怎么把播放器中自带的帧率输出信息给关掉的？就是下面这种信息
"vde avcodec"
"fps 25.56/25.00"
"v-cache 6.6sec"
"a-cache 3.29sec"

**Comment by Rukey7** [comment]
这个是代码中自己把信息显示出来吧，不知道你说的是不是B站Demo中显示的那个？如果是你把InfoHudViewHolder这个处理掉就行了

**Comment by zhangfeisysu** [comment]
就是那个，昨晚我也研究出来了，哈哈，谢了

**Comment by Rukey7** [comment]
不客气
