### ISSUE TITLE
Bilibili/ijkplayer 官方的源码

### ISSUE THREAD

**Issue by xuekaiqi** [Rukey7/IjkPlayerView#2]
从 Bilibili/ijkplayer 下载的源码 不是Android 工程啊！ 这个播放器是你自己封装写的吗？
![image](https://cloud.githubusercontent.com/assets/17778482/20914190/d34e4d20-bbb8-11e6-95eb-7b5a19018161.png)

**Comment by Rukey7** [comment]
从你截图目录进入 android 文件夹，里面的 ijkplayer 就是一个android项目了，编译有报问题可能需要调一下 build.gradle
![image](https://cloud.githubusercontent.com/assets/13436901/20917068/5097b1c0-bbca-11e6-922e-d93e0a00261f.png)

**Comment by xuekaiqi** [comment]
方便加下QQ吗？对你这个开源播放器很感兴趣

**Comment by Rukey7** [comment]
可以，你发个给我我看到加，可以发我邮箱

**Comment by Rukey7** [comment]
可以，你发个给我我看到加，可以发我邮箱

**Comment by Rukey7** [comment]
可以，你发个给我我看到加，可以发我邮箱

**Comment by Rukey7** [comment]
可以，你发个给我我看到加，可以发我邮箱

**Comment by Rukey7** [comment]
可以，你发个给我我看到加，可以发我邮箱

**Comment by Rukey7** [comment]
可以，你发个给我我看到加，可以发我邮箱

**Comment by Rukey7** [comment]
可以，你发个给我我看到加，可以发我邮箱

**Comment by Rukey7** [comment]
你发个Q给我，你账号邮箱那个是不是？

**Comment by xuekaiqi** [comment]
是的    那是我的QQ邮箱
