### ISSUE TITLE
ijkplayer视频分辨率修改

### ISSUE THREAD

**Issue by zy1301529626** [Rukey7/IjkPlayerView#3]
ijkplayer支持分辨率修改 调用哪个方法修改

**Comment by Rukey7** [comment]
确切得说是设置不同的视频播放源，比方说一个视频有清晰、高清和超清3种播放源，你可以通过setVideoSource（）接口来设置，就可以播放的时候去切换了

**Comment by zy1301529626** [comment]
加载视频直播源 晃动时噪点很明显 有没有方法控制噪点？

**Comment by Rukey7** [comment]
抱歉我之前没做直播相关功能，我试着用一个直播地址进行播放，没感觉有什么噪点，你要不直播源发上来我试下

**Comment by zy1301529626** [comment]
您的IjkVideoView 设置渲染器的作用是什么啊？

**Comment by zy1301529626** [comment]
你的QQ多少 加您一下学习一下

**Comment by Rukey7** [comment]
363760359
