### ISSUE TITLE
在模拟器上播放是正常的，点击返回（退出当前activity）奔溃卡死的问题！？

### ISSUE THREAD

**Issue by SkyHots** [Rukey7/IjkPlayerView#32]
在手机上面播放和退出都是没有问题的，我在模拟器上面播放是正常的但是点击返回键退出的的时候手机直接就卡死了，我试过17,22,24的模拟器都出现退出奔溃的情况。   请问blogger或者其他小伙伴 有遇到这种情况吗？ 请给予指导或者建议，谢谢。

**Comment by Rukey7** [comment]
最好别用模拟器测，之前也有反应奇怪的问题，应该和CUP架构有关
