### ISSUE TITLE
怎么实现setRequestedOrientation切换横竖屏的？我在调用这个函数时，只在第一次有效，后面就没切屏效果了。做了什么特殊处理吗？

### ISSUE THREAD

**Issue by bongro** [Rukey7/IjkPlayerView#7]

**Comment by Rukey7** [comment]
你有把参数都配置了吗，android:configChanges，你看下Activity的onConfigurationChanged（）有没有调用到

**Comment by bongro** [comment]
android:configChanges参数配置了，后来加了你源码中的configurationChanged中设置DecorView参数的代码就可以了。感谢！！

**Comment by Rukey7** [comment]
:)
