### ISSUE TITLE
Error:Could not find com.github.Rukey7:IjkPlayerView:1.0.3

### ISSUE THREAD

**Issue by quert999** [Rukey7/IjkPlayerView#8]
照着上面写了工程allprojects里面的maven { url 'https://jitpack.io' }
和module里面的compile 'com.github.Rukey7:IjkPlayerView:1.0.3'
换成compile 'com.github.Rukey7:IjkPlayerView:{lastest-version}'也不行

**Comment by Rukey7** [comment]
这样应该是没问题，你现在还不能用吗，要不截个图看看

**Comment by quert999** [comment]
传文件传不上去。。。
你新建一个项目依赖一下看看啊。。

**Comment by Rukey7** [comment]
我这边肯定可以啊

**Comment by quert999** [comment]
compile 'com.github.Rukey7:IjkPlayerView:v1.0.3'
依赖应该这样写，少了个v，因为release里面是带v的。。。

**Comment by 592308980** [comment]
照着上面写了工程allprojects里面的maven { url 'https://jitpack.io' }
和module里面的compile 'com.github.Rukey7:IjkPlayerView:v1.0.0'
换成compile 'com.github.Rukey7:IjkPlayerView:{lastest-version}'也不行
