### ISSUE TITLE
当视频url中带空格时无法播放 

### ISSUE THREAD

**Issue by zhengliufeng** [Rukey7/IjkPlayerView#9]
当视频url中带空格时无法播放 要怎么解决

**Comment by Rukey7** [comment]
连接地址发个看看，去掉空格后能不能用？

**Comment by zhengliufeng** [comment]
http://xueyuan.mingtaokeji.com/admin/video/d8ff03ff44a483c663fbb1e5284ffa8e/%E8%A1%8C%E4%B8%9A%E9%80%89%E5%93%81 %E5%88%98%E7%8F%82.mp4   去掉空格就无法从服务器获取了  返回404

**Comment by Rukey7** [comment]
你看下这个

**Comment by Rukey7** [comment]
你看下这个 http://blog.csdn.net/oqqquzi1234567/article/details/43409737

**Comment by zhengliufeng** [comment]
哦  好了  非常感谢  你有封装较好的recycleview上拉刷新下拉加载的框架吗  网上试了很多都效果有点不理想

**Comment by Rukey7** [comment]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper 这个可以试下
